name: formaestro_bloc
description: Bloc adapter for formaestro (separate optional package).
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  formaestro:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
