name: formx_example
description: Example app for formaestro.
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  formaestro:
    path: ../

flutter:
  uses-material-design: true
