name: formaestro_example
description: Minimal example for the formaestro package.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  formaestro:
    path: ..

dev_dependencies:
  lints: ^3.0.0

flutter:
  uses-material-design: true
