# Strong, modern lints tuned for packages published on pub.dev.
include: package:lints/recommended.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "build/**"
    - "example/**/.dart_tool/**"
    - ".dart_tool/**"
  errors:
    public_member_api_docs: info
    always_use_package_imports: warning

linter:
  rules:
    - always_use_package_imports
    - avoid_print
    - avoid_redundant_argument_values
    - prefer_const_constructors
    - prefer_final_locals
    - sort_pub_dependencies
    - use_super_parameters
