name: formaestro
description: Reactive, async-first form orchestration for Flutter with cross-field validation and great DX.
version: 1.0.0
homepage: https://github.com/MarciohsjOliveira/formaestro
repository: https://github.com/MarciohsjOliveira/formaestro
issue_tracker: https://github.com/MarciohsjOliveira/formaestro/issues
documentation: https://github.com/MarciohsjOliveira/formaestro#readme

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  mocktail: ^1.0.3
  coverage: ^1.8.0

flutter:
  uses-material-design: true

topics:
  - forms
  - validation
  - state-management
