name: formaestro
description: Reactive, async-first form orchestration for Flutter with cross-field validation and delightful DX.
version: 1.1.0
homepage: https://pub.dev/packages/formaestro
repository: https://github.com/MarciohsjOliveira/formaestro
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
dependencies:
  collection: ^1.18.0 
  flutter:
    sdk: flutter
  meta: ^1.12.0

dev_dependencies:
  coverage: ^1.7.2
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  mocktail: ^1.0.3
  test: ^1.25.0
flutter:
  uses-material-design: true
