name: bloc_example
description: Formaestro + BLoC example
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  formaestro:
    path: ../../../
  formaestro_bloc:
    path: ../../../extras/formaestro_bloc

flutter:
  uses-material-design: true
