name: Feature request
description: Propose a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Thanks for suggesting an idea!"
  - type: input
    id: context
    attributes:
      label: Context
      placeholder: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions you've considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
