name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Versions
        run: |
          flutter --version
          dart --version

      - name: Pub get
        run: flutter pub get

      - name: Format check
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Test with coverage
        run: flutter test --coverage


      - name: Enforce 90% coverage (lib only)
        run: dart tool/coverage_check.dart 90

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: lcov.info
          path: coverage/lcov.info

